Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: com.fun.learning.RequestFunctionalHandler
      CodeUri: D:\gitRepo\AWSPractice\myFirstLamdaFunction
      Runtime: java8